### ISSUE TITLE
Vertical black lines appearing on some transitions

### ISSUE THREAD

**Issue by bondimedical3** [Codeinwp/Nivo-Slider-jQuery#400]
I have installed the latest version of nivo slider from Github and I have noticed on tablets and mobile phones black vertical lines are appearing on some transitions when the effect is set to "random". On Desktop PC's however the transitions appear fine?

**Comment by caleuanhopkins** [comment]
Can you check what version of Nivo Slider you're running please?

**Comment by bondimedical3** [comment]
It is the latest version I downloaded from here. This is occurring on all nivoslider demos I see on the Internet

**Comment by stederrickh** [comment]
Why is this closed? This doesn't help others trying to solve the same issue.
